### ISSUE TITLE
pkgs.toPrettyJSON does not exist

### ISSUE THREAD

**Issue by VanCoding** [johnalotoski/openziti-bins#2]
Hi & Thanks for doing all this awesome work!

I've tried to set this up with a router, controller and console, but in the `ziti-controller.nix` a `pkgs.toPrettyJSON` function is referenced, that does not exist. I wonder where this should come from? Was this part of nixpkgs at some point?

**Comment by johnalotoski** [comment]
Hi @VanCoding, good point and sorry for the confusion. `toPrettyJSON` was a small package added via [overlay](https://github.com/input-output-hk/bitte/blob/master/overlay.nix#L93) from another project and is defined [here](https://github.com/input-output-hk/bitte/blob/master/pkgs/to-pretty-json.nix).

While Ziti was great for some things I was working on in the past, I'm no longer using this product and it looks like the last commit was about 1.5 years ago, so I'd be surprised if these modules still work properly with newer Ziti binaries.

In fact, I have fuzzy recollection that around the time I stopped using it, Ziti was changing the setup/bootstrapping scripts significantly, implying that the bootstrapping scripts found in these nix modules, like [here](https://github.com/johnalotoski/openziti-bins/blob/main/modules/ziti-controller.nix#L250-L286) for example, are probably quite broken now for any recent releases and probably in need of significant rework.

**Comment by VanCoding** [comment]
@johnalotoski Ah, I see, thanks for pointing this out. I'll probably look into re-packaging it then. Your work could still prove useful as a reference, though :)
