### ISSUE TITLE
what is this for?  re openziti-bins ?  there is not even a sentence indicating its purpose

### ISSUE THREAD

**Issue by bmullan** [johnalotoski/openziti-bins#3]

**Comment by johnalotoski** [comment]
I added a repo description since there seems to be recent interest in this.  This repo would need an overhaul to work with any recent OpenZiti versions.  Ex, see: issue https://github.com/johnalotoski/openziti-bins/issues/2.  I'll move this repo to archived to indicate its unmaintained status.
